### PR TITLE
removed old unused code, fixed strtofloat bug

### PR DESCRIPTION
**Pull request by tigrazone**
when read ini file I have a bug<br><a target="_blank" href="https://camo.githubusercontent.com/1405f69823353dc432b89affe7aa1d9d8b7d8055/687474703a2f2f6d6f6f2e686f2e75612f737572662d696365312e706e67"></a><br>
and then<br><a target="_blank" href="https://camo.githubusercontent.com/8e62c38faee3a557ed5913a145e533bb1fd39ab9/687474703a2f2f6d6f6f2e686f2e75612f737572662d696365322e706e67"></a><br>and program start to work like broken - no model, menu is broken

### CODE REVIEW

**Comment by neurolabusc** [comment]
@tigrazone can you tell me what version of Lazarus you are using? I am unable to replicate your issue with Lazarus 1.8.2 on Windows or Lazarus SVN 1.9 on MacOS. strtofloat is a core Lazarus function, so if it is a problem we should get it fixed at the source. Also, can you attach an ini file that generates this error, just in case the issue is there. If you are using a version of Lazarus prior to 1.8.2 can you try upgrading to this latest stable version.  I think this will fix your issue and the new version has a lot of other nice benefits.

**Comment by neurolabusc** [comment]
@tigrazone - one other question. What is your decimal separator. Do you write "0.35" or "0,35"? The manunit.pas does specify `DefaultFormatSettings.DecimalSeparator := '.';`, but it might be nice to rule out this possibility.

**Comment by tigrazone** [comment]
I use last lazarus on Windows 7.
ini file created by surf-ice. 
somethimes open ok, sometimes with error.
val procedure is older but dont give issues

**Comment by neurolabusc** [comment]
Can you please test the current code. The issue is that your system is set to use ',' as the decimal separator, while mine uses '.'. 

I prefer to use floattostr as it generates a dialog if there is an error. This informs the user of the issue and we can fix it. In your implementation, any invalid value is converted to a zero without the user knowing there has been a problem. In this case, where the color bar should be 3.5% of the screen space, your solution would make the colorer require 0%: it would be invisible and the user would not know why.

Thanks for alerting me to this problem.

**Comment by tigrazone** [comment]
it helps!
your approach fix issue

**Pull request closed without merging**
